server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: ${PORT}
spring:
  profiles:
    active:
      - prod
  datasource:
    url: jdbc:mysql://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DBNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

cloud:
  aws:
    s3:
      bucket: ${S3.BUCKET}
      domain: ${S3.DOMAIN}
    credentials:
      access-key: ${S3.ACCESSKEY}
      secret-key: ${S3.SECRETKEY}
    region:
      static: ${S3.REGION}
      auto: false
    stack:
      auto: false

my-env:
  jwt:
    key: ${JWT.KEY}


logging:
  level:
    com.example.baseballprediction: DEBUG